
server:
    port: 8081

spring:
    application:
        name: PAYMENT-SERVICE
    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:3306/payment-db
        username: root
        password: 1234
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
        hibernate:
            ddl-auto: update
    config:
        import: configserver:http://localhost:9296

## CONFIGS ARE LOADED FROM GIT CONFIG SERVER
#eureka:
#    instance:
#        prefer-ip-address: true
#    client:
#        fetch-registry: true
#        register-with-eureka: true
#        service-url:
#            defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}